name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  CI:
    runs-on: ubuntu-lates
    steps:
    - name: Checkups
      uses: actions/checkout@v4
    - name: Build Setup
      uses: actions/setup-node@v3
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
